### ISSUE TITLE
Design token value map

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-button#180]
## Is your feature request related to a problem? Please describe.

Switching a theme should be as easy as swapping out one design token lib for another. The problem is that the Scss for the auro-button element's Scss uses tokens directly as the value per CSS property. 

```scss
  // auro-button--tertiary
  &--tertiary {
    background-color: var(--auro-color-background-lighter);
    border-color: var(--auro-color-ui-default-on-light);
    box-shadow: inset 0 0 0 3px var(--auro-color-ui-default-on-light);
  }
```

## Describe the solution you'd like

A proposed solution is to create a mapping from any pre-defined list of design tokens to a more generic set of values. A possible solution is to use fallback values. 

```scss
  // auro-button--tertiary
  &--tertiary {
    background-color: var(--auro-color-background-lighter, var(--airstream-color-background-lighter));
    border-color: var(--auro-color-ui-default-on-light, var(--airstream-color-ui-default-on-light));
    box-shadow: inset 0 0 0 3px var(--auro-color-ui-default-on-light, var(--airstream-color-ui-default-on-light));
  }
```

While this simplifies the addition of the different themes, this also means that we need to update individual element Scss if there are changes. 

Another way to consider this is to have a single map.scss file that uses a fallback method to redefine the value of generically used tokens. It is assumed that we could create this from the tokens repo. 

```scss
:root {
  --color-background-lighter: var(--auro-color-background-lighter, var(--airstream-color-background-lighter))
  --color-ui-default-on-light: var(--auro-color-ui-default-on-light, var(--airstream-color-ui-default-on-light))
}
```

Then the SCSS would be the following. 

```scss
  // auro-button--tertiary
  &--tertiary {
    background-color: var(--color-background-lighter);
    border-color: var(--color-ui-default-on-light);
  }
```
